version: "3.9"
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend

  apache:
    build: ./apache
    restart: always
    ports:
      - "8080:8080"
    networks:
      backend:
        ipv4_address: 172.20.0.3

networks:
  backend:
    name: backend
    ipam:
      driver: bridge
      config:
        - subnet: 172.20.0.0/24
